### ISSUE TITLE
Use bootstrap ui plugin maybe?

### ISSUE THREAD

**Issue by dereuromark** [backstageel/cakephp-gentelella-theme#3]
Just wondering:
Couldnt https://github.com/backstageel/cakephp-gentelella-theme/blob/master/src/View/Helper/FormHelper.php be removed if one would just build on top of https://github.com/FriendsOfCake/bootstrap-ui plugin?
Because then you can use the full stack of bootstrap and you only need to put a few small CSS or classes on top of it :)

**Comment by backstageel** [comment]
Thanks for the reference... I will test the Theme with Bootstrap UI Plugin and do the update.

**Comment by dereuromark** [comment]
Cool!
Once all is completed and you maybe have a few tests for the remaining classes you can also submit it to https://github.com/FriendsOfCake/awesome-cakephp#skeleton for everyone to more easily find :)
