### ISSUE TITLE
Page in Page issue

### ISSUE THREAD

**Issue by leapswitch** [backstageel/cakephp-gentelella-theme#4]
I am testing this theme. Installed Cakephp , CakeDC Users plugin and the theme. 

Login working fine and redirects me to the home page of gentelella. 

However any other click , example - Additional Pages > Profile , opens it as a page within the main page. Screenshot attached - 
![screenshot from 2016-11-02 19 54 24](https://cloud.githubusercontent.com/assets/1279675/19932484/56d8705a-a136-11e6-866a-64babbc8e758.png)

**Comment by xxBIOSxx** [comment]
also there are errors in some libraries
![error](https://cloud.githubusercontent.com/assets/9299909/19969529/56b9f854-a1af-11e6-9648-d98e9dddabc3.PNG)

**Comment by backstageel** [comment]
The release 1.2.0 is already available which solves this problems.

Keep in mind that you will have to adjust the main menu to fit your application structure
